rootProject.name = "AndroidSample"
include(":app")
include(":buildSrc")
include(":core:base")
include(":common")
include(":core:data")
include(":core:navigation")
include(":features:auth")
include(":features:main")
include(":features:settings")